INSERT INTO parameter(parameter_id,title,unit) VALUES(1001,'Instantaneous air temperature at 2m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1002,'Mean air temperature at 2m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1003,'Minimum air temperature at 2m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1004,'Maximum air temperature at 2m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1011,'Instantaneous temperature at 10m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1012,'Mean air temperature at 10m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1013,'Minimum air temperature at 10m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1014,'Maximum air temperature at 10m','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1021,'Instantaneous temperature in canopy','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1022,'Mean air temperature in canopy','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1023,'Minimum air temperature in canopy','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1024,'Maximum air temperature in canopy','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1101,'Instantaneous temperature at -5cm (Celcius)','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1102,'Mean temperature at -5cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1103,'Minimum temperature at -5cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1104,'Maximum temperature at -5cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1111,'Instantaneous temperature at -10cm (Celcius)','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1112,'Mean temperature at -10cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1113,'Minimum temperature at -10cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1114,'Maximum temperature at -10cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1121,'Instantaneous temperature at -20cm (Celcius)','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1122,'Mean temperature at -20cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1123,'Minimum temperature at -20cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1124,'Maximum temperature at -20cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1131,'Instantaneous temperature at -30cm (Celcius)','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1132,'Mean temperature at -30cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1133,'Minimum temperature at -30cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1134,'Maximum temperature at -30cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1141,'Instantaneous temperature at -40cm (Celcius)','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1142,'Mean temperature at -40cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1143,'Minimum temperature at -40cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1144,'Maximum temperature at -40cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1151,'Instantaneous temperature at -50cm (Celcius)','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1152,'Mean temperature at -50cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1153,'Minimum temperature at -50cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1154,'Maximum temperature at -50cm','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(1901,'Dew point temperature','Celcius');
INSERT INTO parameter(parameter_id,title,unit) VALUES(2001,'Precipitation','mm');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3001,'Instantaneous RH at 2m (%)','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3002,'Mean RH at 2m','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3003,'Minimum RH at 2m','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3004,'Maximum RH at 2m','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3011,'Instantaneous RH at 10m','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3012,'Mean RH at 10m','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3013,'Minimum RH at 10m','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3014,'Maximum RH at 10m','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3021,'Instantaneous RH in canopy','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3022,'Mean RH in canopy','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3023,'Minimum RH in canopy','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3024,'Maximum RH in canopy','%');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3101,'Leaf wetness in 2m (minutes/hour)','minutes/hour');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3102,'Leaf wetness in canopy','minutes/hour');
INSERT INTO parameter(parameter_id,title,unit) VALUES(3103,'Leaf wetness in grass','minutes/hour');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4001,'Wind direction at 2m (degrees 0-360)','degrees');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4002,'Instantaneous wind speed at 2m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4003,'Mean wind speed at 2m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4004,'Max wind speed at 2m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4005,'Min wind speed at 2m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4011,'Wind direction at 10m (degrees 0-360)','degrees');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4012,'Instantaneous wind speed at 10m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4013,'Mean wind speed at 10m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4014,'Max wind speed at 10m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(4015,'Min wind speed at 10m','m/s');
INSERT INTO parameter(parameter_id,title,unit) VALUES(5001,'Solar radiation (Q0) (W/sqm)','W/sqm');
